// Texture-file
// Definitions for Go2POV-files
// created by Go2POV (version )
// If this file exists it will not be overwritten by Go2POV

#declare wood_pigment = pigment{wood color_map{[0.00 color rgb <1.0, 0.8, 0.5>] [0.99 color rgb <0.9, 0.8, 0.5>]} turbulence 0.3 scale 0.1
}
#declare wood_finish = finish {phong 0.2}

#declare grid_pigment = pigment {color rgb<0,0,0>}
#declare grid_finish  = finish{phong 0}

#declare bs_pigment = pigment{color rgb<0,0,0>}
#declare bs_finish = finish{phong 0.2 phong_size 0.8}

#declare ws_pigment = pigment{color rgb<1,1,1>}
#declare ws_finish = finish{phong 1 phong_size 150}

